export const HOME_ROUTE = '/'
export const SUBFOLDER_ROUTE = '/juego'
export const LOGIN_ROUTE = '/iniciar-sesion'
export const REGISTER_ROUTE = '/registro'
export const PANTALLA_INICIO = '/dashboard'
export const MIS_CULTIVOS = '/misCultivos'
export const CONTROL_SENSORES = '/control'
export const ESTADISTICAS_CULTIVOS = '/estadisticas-cultivo'
export const INTRODUCCION_ROUTE = `${SUBFOLDER_ROUTE}/introduccion`
export const MAPA_ROUTE = `${SUBFOLDER_ROUTE}/mapa`
export const ANFORA_ROUTE = `${SUBFOLDER_ROUTE}/anfora`
export const PRUEBA_DIAGNOSTICA_ROUTE = `${SUBFOLDER_ROUTE}/prueba-diagnostica`
export const RESULTADOS_ROUTE = `${SUBFOLDER_ROUTE}/usuarios`
export const MUNDOS_ROUTE = `${SUBFOLDER_ROUTE}/empezar-la-aventura`
export const NUEVO_CULTIVO ='/nuevoCultivo'
export const DETALLE_CULTIVO ="/detalle-cultivo"